[WIP]webページ改修
selelab/web pull request #7
Opened 2020-09-04 11:40 UTC by r5Rin

- トップページ
- 活動内容
- イベントページ

2020-09-05 17:50 UTC, r5Rin commented
ひとまず完成しました。修正点などあれば指摘お願いします。

2020-09-08 10:25 UTC, Tsutomu-Ikeda requested changes
### ファイルサイズを小さくする
pngである必要の無いファイルはjpg形式でお願いします。
- [public/assets/images/hard_00.png](https://github.com/selelab/web/blob/2ea85968f1a5056783364836340e3bfefa4c0c14/public/assets/images/hard_00.png)
- [public/assets/images/hard_01.png](https://github.com/selelab/web/blob/2ea85968f1a5056783364836340e3bfefa4c0c14/public/assets/images/hard_01.png)
- [public/assets/images/hard_02.png](https://github.com/selelab/web/blob/2ea85968f1a5056783364836340e3bfefa4c0c14/public/assets/images/hard_02.png)
- [public/assets/images/hard_03.png](https://github.com/selelab/web/blob/2ea85968f1a5056783364836340e3bfefa4c0c14/public/assets/images/hard_03.png)
- [public/assets/images/index_01.png](https://github.com/selelab/web/blob/2ea85968f1a5056783364836340e3bfefa4c0c14/public/assets/images/index_01.png)
- [public/assets/images/kusatsu.png](https://github.com/selelab/web/blob/2ea85968f1a5056783364836340e3bfefa4c0c14/public/assets/images/kusatsu.png)
- [public/assets/images/soft_00.png](https://github.com/selelab/web/blob/2ea85968f1a5056783364836340e3bfefa4c0c14/public/assets/images/soft_00.png)
- [public/assets/images/soft_01.png](https://github.com/selelab/web/blob/2ea85968f1a5056783364836340e3bfefa4c0c14/public/assets/images/soft_01.png)
- ~[public/assets/images/soft_02.png](https://github.com/selelab/web/blob/2ea85968f1a5056783364836340e3bfefa4c0c14/public/assets/images/soft_02.png)~ こちらはファイルサイズが小さいので、変換しなくても良い
- ~[public/assets/images/soft_03.png](https://github.com/selelab/web/blob/2ea85968f1a5056783364836340e3bfefa4c0c14/public/assets/images/soft_03.png)~ こちらはファイルサイズが小さいので、変換しなくても良い

2020-09-08 10:32 UTC, Tsutomu-Ikeda requested changes
### 404ページの文字色を白くする

[.src/contents/404.js#L15](https://github.com/r5Rin/web/blob/63e2da2db4751a4b6cf68a130952a6689b361e8c/src/contents/404.js#L15)

![image](https://user-images.githubusercontent.com/40418321/92465652-d2979b80-f209-11ea-9ef6-bad03ce94080.png)

2020-09-10 04:29 UTC, r5Rin commented
画像の形式と404ページを修正しました。

2020-09-10 09:43 UTC, Tsutomu-Ikeda commented
### ファイルサイズを小さくする

`hard_02.jpg` と `soft_01.jpg` についてはそもそもの解像度が高くて、ファイルサイズが大きくなってしまっているので、リサイズをお願いします…

```
❯ cd ./public/assets/images
❯ ll | sort -k 5 -rh
-rwxr-xr-x 1 tomtsutom staff 2.6M Sep 10 17:50 hard_02.jpg
-rwxr-xr-x 1 tomtsutom staff 666K Sep 10 17:50 soft_01.jpg
-rwxr-xr-x 1 tomtsutom staff 199K Sep 10 17:50 hard_01.jpg
-rwxr-xr-x 1 tomtsutom staff 174K Sep 10 17:50 kusatsu.jpg
-rwxr-xr-x 1 tomtsutom staff 168K Sep 10 17:50 index_01.jpg
...
```

Chromeの開発者モードで通信速度を `Fast 3G` に設定すると、`hard_02.jpg` は読み込みに20秒近くかかってしまいます…
![image](https://user-images.githubusercontent.com/40418321/92712827-2b476f80-f395-11ea-95ec-6e2904e74996.png)

2020-09-10 09:47 UTC, Tsutomu-Ikeda requested changes
### ファイルサイズを小さくする

`hard_02.jpg` と `soft_01.jpg` についてはそもそもの解像度が高くて、ファイルサイズが大きくなってしまっているので、リサイズをお願いします。 `960x960`以下でちょうど良いと思います。

```
❯ cd ./public/assets/images
❯ ll | sort -k 5 -rh
-rwxr-xr-x 1 tomtsutom staff 2.6M Sep 10 17:50 hard_02.jpg
-rwxr-xr-x 1 tomtsutom staff 666K Sep 10 17:50 soft_01.jpg
-rwxr-xr-x 1 tomtsutom staff 199K Sep 10 17:50 hard_01.jpg
-rwxr-xr-x 1 tomtsutom staff 174K Sep 10 17:50 kusatsu.jpg
-rwxr-xr-x 1 tomtsutom staff 168K Sep 10 17:50 index_01.jpg
...
```

Chromeの開発者モードで通信速度を `Fast 3G` に設定すると、`hard_02.jpg` は読み込みに20秒近くかかってしまいます…
![image](https://user-images.githubusercontent.com/40418321/92712827-2b476f80-f395-11ea-95ec-6e2904e74996.png)

2020-09-10 10:55 UTC, r5Rin commented
画像をリサイズして、使用している画像で一番重いのが199KBになりました。
画像のサイズは深く考えてなかったんですけど、大事ですね・・・

2020-09-16 08:13 UTC, Tsutomu-Ikeda commented on src/contents/Top.js
> +      </Typography>
今年の予定とも読めてしまうので、文言修正をお願いします 🙇 
```diff
      <Typography weight={"bold"} variant={"h5"} gutterBottom>
-        年間イベント
+        年間イベント(2019年実績)
      </Typography>
```

2020-09-19 11:32 UTC, Tsutomu-Ikeda approved these changes
良いでしょう。

2020-09-19 11:33 UTC, merged